services:
  - type: web
    name: nutrition-predict-api
    env: python
    buildCommand: bash .render/build.sh
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyB0bePVOwK-stx67SiQqf0EEpVJroP8LrE
