services:
  - type: web
    name: nutrition-predict-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyB0bePVOwK-stx67SiQqf0EEpVJroP8LrE
